apiVersion: v1
kind: Service
metadata:
  name: shipment-service
  labels:
    run: shipment-service
spec:
  ports:
    - port: 9094
      targetPort: 9094
      protocol: TCP
  selector:
    app: shipment-service
