apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    run: order-service
spec:
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: order-service
