apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    run: payment-service
spec:
  ports:
    - port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: payment-service
