apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    run: product-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: product-service
